# Activity I - Task 2

In [1]:
# Creating matrix (2D list) from Tuple
#Day1 = [[(0.8,1,0.5),(1,0.9,0.6),(1,1,0.5)]]
#Day2= [[(0.3,1.2,0.7),(0.5,1.1,0.8),(0.5,1.3,0.7)]]

#or
# Creating matrix from lists

Day1 = [[0.8,1,0.5],[1,0.9,0.6],[1,1,0.5]]
Day2= [[0.3,1.2,0.7],[0.5,1.1,0.8],[0.5,1.3,0.7]]

In [2]:
import numpy as np

In [3]:
A = np.array(Day1)
B = np.array(Day2)

In [4]:
type(A)

numpy.ndarray

In [5]:
type(Day1)

list

In [6]:
# Dimensions of an arrary
A.shape

(3, 3)

In [7]:
# No of elements in an array
A.size

9

In [8]:
A.ndim

2

In [9]:
print(A[0,1])

1.0


In [10]:
print(A[:,2])

[0.5 0.6 0.5]


In [11]:
time_spent = A + B
print(time_spent)

[[1.1 2.2 1.2]
 [1.5 2.  1.4]
 [1.5 2.3 1.2]]


Sample on matrix multiplication

In [12]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[5,6,7],[8,9,10],[11,12,13]])

In [13]:
np.dot(x,y)

array([[ 54,  60,  66],
       [126, 141, 156]])

In [14]:
np.matmul(x,y)

array([[ 54,  60,  66],
       [126, 141, 156]])

In [15]:
x@y

array([[ 54,  60,  66],
       [126, 141, 156]])

In [16]:
row,col = x.shape

In [17]:
row

2

In [18]:
col

3

In [19]:
w = np.array(((2,3),(4,5)))
z = np.array(((5,6),(7,8)))

In [20]:
w*z

array([[10, 18],
       [28, 40]])