Activity 1 - Task 2

In [3]:
# Creating matrix (2D list) from Tuple
#Day1 = [[(0.8,1,0.5),(1,0.9,0.6),(1,1,0.5)]]
#Day2= [[(0.3,1.2,0.7),(0.5,1.1,0.8),(0.5,1.3,0.7)]]

#or
# Creating matrix from lists

Day1 = [[0.8,1,0.5],[1,0.9,0.6],[1,1,0.5]]
Day2= [[0.3,1.2,0.7],[0.5,1.1,0.8],[0.5,1.3,0.7]]

In [4]:
import numpy as np

In [5]:
A = np.array(Day1)

In [6]:
type(A)

numpy.ndarray

In [7]:
type(Day1)

list

In [13]:
# Dimensions of an arrary
A.shape

(3, 3)

In [14]:
# No of elements in an array
A.size

9

In [15]:
A.ndim

2

Activity 2

In [16]:
population = np.array([17820, 68966, 24965, 3952, 13655,
                   14437, 37150, 46316, 23632, 28740,
                   35079, 62590, 46004,138736, 17300,
                   45518, 19960, 22376, 42186, 17736])

In [17]:
population.shape

(20,)

In [18]:
population.size

20

In [19]:
population.ndim

1

In [30]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[5,6,7],[8,9,10],[11,12,13]])

In [31]:
np.dot(x,y)

array([[ 54,  60,  66],
       [126, 141, 156]])

In [32]:
np.matmul(x,y)

array([[ 54,  60,  66],
       [126, 141, 156]])

In [33]:
x@y

array([[ 54,  60,  66],
       [126, 141, 156]])

In [37]:
row,col = x.shape

In [38]:
row

2

In [39]:
col

3

In [47]:
w = np.array(((2,3),(4,5)))
z = np.array(((5,6),(7,8)))

In [48]:
w*z

array([[10, 18],
       [28, 40]])